//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Login = new HashSet<Login>();
            this.Paiban = new HashSet<Paiban>();
        }
    
        public int YsID { get; set; }
        public string Yname { get; set; }
        public string Yphone { get; set; }
        public string Yzhuzhi { get; set; }
        public string Yjianjie { get; set; }
        public string Yzhicheng { get; set; }
        public string Ysex { get; set; }
        public string Yold { get; set; }
        public string Yphoto { get; set; }
        public Nullable<int> Bid { get; set; }
        public string Ystate { get; set; }
    
        public virtual Bumen Bumen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiban> Paiban { get; set; }
    }
}
