//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guahao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guahao()
        {
            this.Morder = new HashSet<Morder>();
            this.Zhuyuan = new HashSet<Zhuyuan>();
        }
    
        public int Gid { get; set; }
        public string Gname { get; set; }
        public string GPhone { get; set; }
        public string Gshenfenzheng { get; set; }
        public string GSex { get; set; }
        public string Gbingli { get; set; }
        public Nullable<int> YsID { get; set; }
        public string Gstate { get; set; }
        public int Pid { get; set; }
        public System.DateTime Gtime { get; set; }
    
        public virtual Paiban Paiban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morder> Morder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zhuyuan> Zhuyuan { get; set; }
    }
}
