//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Morder = new HashSet<Morder>();
        }
    
        public int medicineID { get; set; }
        public string Mname { get; set; }
        public int Mshu { get; set; }
        public string Mdanwei { get; set; }
        public string Mdizhi { get; set; }
        public string Mliaoxiao { get; set; }
        public decimal Mmoneyj { get; set; }
        public decimal Mmoneyc { get; set; }
        public System.DateTime Mshengchan { get; set; }
        public System.DateTime Mguoqi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morder> Morder { get; set; }
    }
}
