//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDBEntities : DbContext
    {
        public HospitalDBEntities()
            : base("name=HospitalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bumen> Bumen { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Guahao> Guahao { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Morder> Morder { get; set; }
        public virtual DbSet<Paiban> Paiban { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Wx> Wx { get; set; }
        public virtual DbSet<Xiangmu> Xiangmu { get; set; }
        public virtual DbSet<Zhuyuan> Zhuyuan { get; set; }
    }
}
