//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morder
    {
        public int OrderIDm { get; set; }
        public int medicineID { get; set; }
        public Nullable<int> Gid { get; set; }
        public int Mshu { get; set; }
        public string state { get; set; }
        public string miaoshu { get; set; }
        public string zhifu { get; set; }
        public string mhz { get; set; }
    
        public virtual Guahao Guahao { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
