//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paiban()
        {
            this.Guahao = new HashSet<Guahao>();
        }
    
        public int Pid { get; set; }
        public System.TimeSpan Ptimek { get; set; }
        public System.TimeSpan Ptimej { get; set; }
        public int YsID { get; set; }
        public decimal Pmoney { get; set; }
        public string Pstate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guahao> Guahao { get; set; }
    }
}
