//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zhuyuan
    {
        public int Zhuid { get; set; }
        public int Gid { get; set; }
        public string Ke { get; set; }
        public Nullable<int> Chuang { get; set; }
        public string state { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> riqi { get; set; }
        public Nullable<System.DateTime> riqic { get; set; }
        public Nullable<decimal> moneyz { get; set; }
    
        public virtual Guahao Guahao { get; set; }
    }
}
